##### Exercises are got from
https://towardsdatascience.com/advanced-numpy-master-stride-tricks-with-25-illustrated-exercises-923a9393ab20#4838

In [2]:
import numpy as np


In [6]:
a = np.random.randn(10)
print(a.itemsize) # Each item is 8 bytes
print(a.strides) # To jump to next item, we need 8 bytes

8
(8,)


In [7]:
# Exericse 1. Slice first 3 elements
a = np.arange(1,26).reshape(5,5).astype(np.int8)
print(a.itemsize)
print(a.strides)
np.lib.stride_tricks.as_strided(a, shape=(3,), strides=(1,))


1
(5, 1)


array([1, 2, 3], dtype=int8)

In [8]:
# Exericse 2. Slice first 8 elements
a = np.arange(1,26).reshape(5,5).astype(np.int8)
print(a.itemsize)
print(a.strides)
np.lib.stride_tricks.as_strided(a, shape=(8,), strides=(1,))


1
(5, 1)


array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int8)

In [9]:
# Exericse 3. Flatten
a = np.arange(1,26).reshape(5,5).astype(np.int16)
print(a.itemsize)
print(a.strides)
np.lib.stride_tricks.as_strided(a, shape=(25,), strides=(2,))


2
(10, 2)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25], dtype=int16)

In [10]:

# Exericse 4. Skipping every other elements
a = np.arange(1,26).reshape(5,5).astype(np.int8)
print(a.itemsize)
print(a.strides)
np.lib.stride_tricks.as_strided(a, shape=(3,), strides=(2,))

1
(5, 1)


array([1, 3, 5], dtype=int8)

In [11]:

# Exericse 5. Slicing the first column
a = np.arange(1,26).reshape(5,5).astype(np.int64)
print(a.itemsize)
print(a.strides)
np.lib.stride_tricks.as_strided(a, shape=(4,), strides=(40,))

8
(40, 8)


array([ 1,  6, 11, 16])

In [12]:

# Exericse 6. Slicing the diagonal
a = np.arange(1,26).reshape(5,5).astype(np.int64)
print(a.itemsize)
print(a.strides)
np.lib.stride_tricks.as_strided(a, shape=(5,), strides=(48,))

8
(40, 8)


array([ 1,  7, 13, 19, 25])

In [13]:
# Exericse 7. Repeating the first element
a = np.arange(1,26).reshape(5,5).astype(np.int64)
print(a.itemsize)
print(a.strides)
np.lib.stride_tricks.as_strided(a, shape=(5,), strides=(0,))

8
(40, 8)


array([1, 1, 1, 1, 1])

In [16]:
# Exericse 8. Repeating the first element
a = np.arange(1,26).reshape(5,5).astype(np.int64)
print(a.itemsize)
print(a.strides)
np.lib.stride_tricks.as_strided(a, shape=(3,4), strides=(40,8))

8
(40, 8)


array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]])

In [18]:
# Exericse 9. Slicing a zigzav
a = np.arange(1,26).reshape(5,5).astype(np.int64)
print(a.itemsize)
print(a.strides)
np.lib.stride_tricks.as_strided(a, shape=(4,2), strides=(48,8))

8
(40, 8)


array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20]])

In [21]:
# Exericse 10. Sparse slicing
a = np.arange(1,26).reshape(5,5).astype(np.int64)
print(a.itemsize)
print(a.strides)
np.lib.stride_tricks.as_strided(a, shape=(3,3), strides=(80,16))

8
(40, 8)


array([[ 1,  3,  5],
       [11, 13, 15],
       [21, 23, 25]])

In [23]:
# Exericse 11. Sparse slicing
a = np.arange(1,26).reshape(5,5).astype(np.int8)
print(a.itemsize)
print(a.strides)
np.lib.stride_tricks.as_strided(a, shape=(3,3), strides=(1,5))

1
(5, 1)


array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13]], dtype=int8)

In [25]:
# Exericse 12. Repeat first column 4 times
a = np.arange(1,26).reshape(5,5).astype(np.int32)
print(a.itemsize)
print(a.strides)
np.lib.stride_tricks.as_strided(a, shape=(5,4), strides=(20,0))

4
(20, 4)


array([[ 1,  1,  1,  1],
       [ 6,  6,  6,  6],
       [11, 11, 11, 11],
       [16, 16, 16, 16],
       [21, 21, 21, 21]], dtype=int32)

In [26]:
# Exercise 13. Reshape 1D to 2D
a = np.arange(1,13).astype(np.int64)
print(a.itemsize)
print(a.strides)
np.lib.stride_tricks.as_strided(a, shape=(4,3), strides=(24, 8))

8
(8,)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [28]:
# Exercise 14. Sliding a 1D window
a = np.arange(1,11).astype(np.int8)
print(a.itemsize)
print(a.strides)
np.lib.stride_tricks.as_strided(a, shape=(8,3), strides=(1, 1))

1
(1,)


array([[ 1,  2,  3],
       [ 2,  3,  4],
       [ 3,  4,  5],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10]], dtype=int8)

In [30]:
# Exercise 15. Sliding a 2D window then flatten
a = np.array([[0,1],[10,11],[20,21],[30,31],[40,41],[50,51]]).astype(np.int8)
print(a.itemsize)
print(a.strides)
np.lib.stride_tricks.as_strided(a, shape=(4,6), strides=(2, 1))

1
(2, 1)


array([[ 0,  1, 10, 11, 20, 21],
       [10, 11, 20, 21, 30, 31],
       [20, 21, 30, 31, 40, 41],
       [30, 31, 40, 41, 50, 51]], dtype=int8)

In [31]:
# Exercise 16. Collapse an axis from a 3D array
a = np.arange(1,13).reshape(3,2,2).astype(np.int8)
print(a.itemsize)
print(a.strides)
np.lib.stride_tricks.as_strided(a, shape=(3,4), strides=(4, 1))

1
(4, 2, 1)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int8)

In [33]:
# Exercise 17. 3D 2 corners
a = np.arange(1,26).reshape(5,5).astype(np.int16)
print(a.itemsize)
print(a.strides)
np.lib.stride_tricks.as_strided(a, (2,2,2), strides=(30, 10,2))

2
(10, 2)


array([[[ 1,  2],
        [ 6,  7]],

       [[16, 17],
        [21, 22]]], dtype=int16)

In [34]:
# Exercise 18. 3D Staggered slicing
a = np.arange(1,26).reshape(5,5).astype(np.int8)
print(a.itemsize)
print(a.strides)
np.lib.stride_tricks.as_strided(a, (2,2,3), strides=(10, 6,1))

1
(5, 1)


array([[[ 1,  2,  3],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [17, 18, 19]]], dtype=int8)

In [36]:
# Exercise 19. Repeat 2D array
a = np.arange(1,26).reshape(5,5).astype(np.int16)
print(a.itemsize)
print(a.strides)
np.lib.stride_tricks.as_strided(a, (3,2,4), strides=(0, 10,2))

2
(10, 2)


array([[[1, 2, 3, 4],
        [6, 7, 8, 9]],

       [[1, 2, 3, 4],
        [6, 7, 8, 9]],

       [[1, 2, 3, 4],
        [6, 7, 8, 9]]], dtype=int16)

In [37]:
# Exercise 20. 3D transpose
a = np.arange(1,13).reshape(3,2,2).astype(np.int32)
print(a.itemsize)
print(a.strides)
np.lib.stride_tricks.as_strided(a, (3,2,2), strides=(16, 4, 8))

4
(16, 8, 4)


array([[[ 1,  3],
        [ 2,  4]],

       [[ 5,  7],
        [ 6,  8]],

       [[ 9, 11],
        [10, 12]]], dtype=int32)

In [38]:
# Exercise 20. 3D transpose
a = np.arange(1,21).reshape(4,5).astype(np.int64)
print(a.itemsize)
print(a.strides)
np.lib.stride_tricks.as_strided(a, (3,2,5), strides=(40, 40, 8))

8
(40, 8)


array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [40]:
# Exercise 21. Reshape 1D to 3D
a = np.arange(1,13).astype(np.int8)
print(a.itemsize)
print(a.strides)
np.lib.stride_tricks.as_strided(a, (2,2,3), strides=(6, 3, 1))

1
(1,)


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int8)

In [46]:
# Exercise 23
a = np.arange(1,26).reshape(5,5).astype(np.int8)
print(a.itemsize)
print(a.strides)
np.lib.stride_tricks.as_strided(a, (2,2,3,3), strides=(10,2,5,1))

1
(5, 1)


array([[[[ 1,  2,  3],
         [ 6,  7,  8],
         [11, 12, 13]],

        [[ 3,  4,  5],
         [ 8,  9, 10],
         [13, 14, 15]]],


       [[[11, 12, 13],
         [16, 17, 18],
         [21, 22, 23]],

        [[13, 14, 15],
         [18, 19, 20],
         [23, 24, 25]]]], dtype=int8)

In [47]:
# Exercise 24
a = np.arange(1,13).reshape(2,2,3).astype(np.int64)
print(a.itemsize)
print(a.strides)
np.lib.stride_tricks.as_strided(a, (2,2,2,3), strides=(48,0,24,8))

8
(48, 24, 8)


array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 1,  2,  3],
         [ 4,  5,  6]]],


       [[[ 7,  8,  9],
         [10, 11, 12]],

        [[ 7,  8,  9],
         [10, 11, 12]]]])

In [48]:
# Exercise 25
a = np.arange(1,17).astype(np.int64)
print(a.itemsize)
print(a.strides)
np.lib.stride_tricks.as_strided(a, (2,2,2,2), strides=(64,32,16,8))

8
(8,)


array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])